platform :ios, '9.0'

target 'MVVMAdditions' do
  use_frameworks!

  pod 'RxSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'KeychainSwift'
  pod 'EventBusSwift'
 
  target 'MVVMAdditionsTests' do
      inherit! :search_paths
  end

end
